export enum EstadoInstalacionCliente {
  PROGRAMADA = "PROGRAMADA",
  EN_PROCESO = "EN_PROCESO",
  COMPLETADA = "COMPLETADA",
  CANCELADA = "CANCELADA",
  FALLIDA = "FALLIDA",
  REPROGRAMADA = "REPROGRAMADA",
}

export enum TipoInstalacionCliente {
  NUEVA = "NUEVA",
  REINSTALACION = "REINSTALACION",
  TRASLADO = "TRASLADO",
  CAMBIO_EQUIPO = "CAMBIO_EQUIPO",
  MIGRACION_PLAN = "MIGRACION_PLAN",
  MIGRACION_TECNOLOGIA = "MIGRACION_TECNOLOGIA",
  OTRO = "OTRO",
}
export enum RolTecnicoOperacionCliente {
  RESPONSABLE = "RESPONSABLE",
  APOYO = "APOYO",
  SUPERVISOR = "SUPERVISOR",
  COBRADOR = "COBRADOR",
  OTRO = "OTRO",
}

export enum TipoEvidenciaClienteOperacion {
  ANTES = "ANTES",
  DESPUES = "DESPUES",
  EQUIPO = "EQUIPO",
  ROUTER = "ROUTER",
  ONU = "ONU",
  ANTENA = "ANTENA",
  CABLEADO = "CABLEADO",
  UBICACION = "UBICACION",
  FIRMA = "FIRMA",
  BOLETA = "BOLETA",
  RECIBO = "RECIBO",
  DOCUMENTO = "DOCUMENTO",
  OTRO = "OTRO",
}

// export enum RolTecnicoOperacionCliente {
//   RESPONSABLE = "RESPONSABLE",
//   APOYO = "APOYO",
//   SUPERVISOR = "SUPERVISOR",
//   COBRADOR = "COBRADOR",
//   OTRO = "OTRO",
// }
