import type { Route } from "./crm-route-types";
import {
  botMensajeriaRoute,
  campaniasWhatsappRoute,
  clientesRoute,
  creditosRoute,
  dashboardRoute,
  desinstalacionesRoute,
  facturacionZonaRoute,
  instalacionesRoute,
  perfilRoute,
  plantillasContratosRoute,
  pppoeRoute,
  registrosEliminadosRoute,
  reportsRoute,
  rutasCobroRoute,
  sectoresRoute,
  // serviciosRoute,
  soporteRoute,
} from "./crm-route-items";

export const routesCrm_Admin: Route[] = [
  dashboardRoute,
  clientesRoute,
  instalacionesRoute,
  soporteRoute,
  desinstalacionesRoute,
  // serviciosRoute,
  facturacionZonaRoute,
  sectoresRoute,
  botMensajeriaRoute,
  campaniasWhatsappRoute,
  plantillasContratosRoute,
  rutasCobroRoute,
  // opticoRoute,
  creditosRoute,
  registrosEliminadosRoute,
  reportsRoute,
  perfilRoute,
  pppoeRoute,
];
