import type { Route } from "./crm-route-types";
import {
  botMensajeriaRoute,
  clientesRoute,
  creditosRoute,
  dashboardRoute,
  desinstalacionesRoute,
  facturacionZonaRoute,
  instalacionesRoute,
  opticoRoute,
  perfilRoute,
  plantillasContratosRoute,
  pppoeRoute,
  registrosEliminadosRoute,
  reportsRoute,
  rutasCobroRoute,
  sectoresRoute,
  serviciosRoute,
  soporteRoute,
  usuariosRoute,
} from "./crm-route-items";

export const routesCrm_SuperAdmin: Route[] = [
  dashboardRoute,
  clientesRoute,
  instalacionesRoute,
  soporteRoute,
  desinstalacionesRoute,
  serviciosRoute,
  facturacionZonaRoute,
  sectoresRoute,
  botMensajeriaRoute,
  plantillasContratosRoute,
  rutasCobroRoute,
  opticoRoute,
  creditosRoute,
  registrosEliminadosRoute,
  reportsRoute,
  perfilRoute,
  usuariosRoute,
  pppoeRoute,
];
