import {
  ClienteDetailsDto,
  EstadoServicioMikrotik,
} from "@/Crm/features/cliente-interfaces/cliente-types";

export const clienteInitialState: ClienteDetailsDto = {
  id: 0,
  nombre: "",
  apellidos: "",
  telefono: "",
  direccion: "",
  dpi: "",
  observaciones: "",
  contactoReferenciaNombre: "",
  contactoReferenciaTelefono: "",
  estadoCliente: "",
  contrasenaWifi: "",
  ssidRouter: "",
  fechaInstalacion: "",
  // Relaciones requeridas con valores "placeholder" seguros
  sector: {
    id: 0,
    nombre: "",
    actualizadoEn: "",
    creadoEn: "",
    descripcion: "",
    municipioId: 0,
    clientes: [],
    municipio: {
      id: 0,
      nombre: "",
    },
  },
  municipio: { id: 0, nombre: "" },
  departamento: { id: 0, nombre: "" },
  empresa: {
    id: 0,
    nombre: "",
    direccion: "",
    correo: "",
    pbx: "",
    sitioWeb: "",
    telefono: "",
    nit: "",
  },
  IP: {
    id: 0,
    direccion: "192.168.100.1", // como tenías
    mascara: "",
    gateway: "",
  },
  ubicacion: {
    id: 0,
    latitud: 15.667147636975496,
    longitud: -91.71722598563508,
  },
  // Relaciones opcionales / listas vacías
  asesor: null,
  servicio: null,
  saldoCliente: null,
  ticketSoporte: [],
  facturaInternet: [],
  clienteServicio: [],
  contratoServicioInternet: null,
  creadoEn: "",
  actualizadoEn: "",
  imagenes: [],
  mikrotik: {
    activo: true,
    actualizadoEn: "",
    creadoEn: "",
    empresaId: 1,
    host: "",
    id: 1,
    nombre: "",
    passwordEnc: "",
    sshPort: 1,
    usuario: "",
  },
  estadoServicioMikrotik: EstadoServicioMikrotik.ACTIVO,
  servicioEstado: true,
  facturacionZona: {
    actualizadoEn: "",
    creadoEn: "",
    diaGeneracionFactura: 1,
    diaPago: 1,
    diaRecordatorio: 1,
    diaSegundoRecordatorio: 1,
    empresaId: 1,
    enviarAvisoPago: true,
    enviarRecordatorio: true,
    enviarRecordatorio1: true,
    enviarRecordatorio2: true,
    enviarRecordatorioGeneracion: true,
    horaRecordatorio: "",
    nombre: "",
    diaCorte: 1,
    email: false,
    llamada: false,
    sms: false,
    suspenderTrasFacturas: 1,
    telegram: false,
    whatsapp: false,
  },
};
