import { RolUsuario } from "@/Crm/features/users/users-rol";
import { CRM_PERMISSION, type CrmPermission } from "./crm-permissions";

// AGRUPAMIENTOS
const PPPOE_FULL_PERMISSIONS: readonly CrmPermission[] = [
  CRM_PERMISSION.PPPOE_HOMOLOGACIONES_VER,

  CRM_PERMISSION.PPPOE_AUDITORIA_VER,
  CRM_PERMISSION.PPPOE_OPERACIONES_VER,
  CRM_PERMISSION.PPPOE_ADMINISTRACION_VER,

  CRM_PERMISSION.PPPOE_ACTIVAR_INICIAL,
  CRM_PERMISSION.PPPOE_OPERACIONES_REINTENTAR,
  CRM_PERMISSION.PPPOE_PREALTA_REINTENTAR,

  CRM_PERMISSION.PPPOE_SUSPENDER,
  CRM_PERMISSION.PPPOE_REACTIVAR,

  CRM_PERMISSION.PPPOE_CREDENCIALES_REVELAR,

  CRM_PERMISSION.PPPOE_DIAGNOSTICO_SENSIBLE_VER,
];

const PPPOE_OFICINA_PERMISSIONS: readonly CrmPermission[] = [
  CRM_PERMISSION.PPPOE_ADMINISTRACION_VER,

  CRM_PERMISSION.PPPOE_ACTIVAR_INICIAL,
  CRM_PERMISSION.PPPOE_SUSPENDER,
  CRM_PERMISSION.PPPOE_REACTIVAR,

  CRM_PERMISSION.PPPOE_CREDENCIALES_REVELAR,
];
// AGRUPAMIENTOS

const ADMIN_PERMISSIONS: readonly CrmPermission[] = [
  CRM_PERMISSION.DASHBOARD_VER,

  CRM_PERMISSION.CLIENTES_VER,
  CRM_PERMISSION.CLIENTES_CREAR,
  CRM_PERMISSION.CLIENTES_EDITAR,

  CRM_PERMISSION.INSTALACIONES_VER,
  CRM_PERMISSION.INSTALACIONES_CREAR,
  CRM_PERMISSION.INSTALACIONES_EDITAR,

  CRM_PERMISSION.TICKETS_VER,
  CRM_PERMISSION.SOPORTE_METAS_VER,
  CRM_PERMISSION.SOPORTE_CATEGORIAS_VER,

  CRM_PERMISSION.DESINSTALACIONES_VER,
  CRM_PERMISSION.DESINSTALACIONES_CREAR,
  CRM_PERMISSION.DESINSTALACIONES_AUTORIZAR,

  CRM_PERMISSION.SERVICIOS_VER,

  CRM_PERMISSION.FACTURACION_ZONA_VER,
  CRM_PERMISSION.PAGOS_GESTIONAR,
  CRM_PERMISSION.SECTORES_VER,

  CRM_PERMISSION.BOT_VER,
  CRM_PERMISSION.WHATSAPP_VER,
  CRM_PERMISSION.WHATSAPP_GALERIA_VER,
  CRM_PERMISSION.WHATSAPP_PLANTILLAS_VER,
  CRM_PERMISSION.WHATSAPP_CAMPANAS_VER,

  CRM_PERMISSION.PLANTILLAS_CONTRATO_VER,

  CRM_PERMISSION.RUTAS_COBRO_VER,
  CRM_PERMISSION.RUTAS_ASIGNADAS_VER,

  CRM_PERMISSION.OPTICO_VER,

  CRM_PERMISSION.CREDITOS_VER,
  CRM_PERMISSION.CREDITOS_CREAR,

  CRM_PERMISSION.REGISTROS_ELIMINADOS_VER,

  CRM_PERMISSION.REPORTES_VER,

  CRM_PERMISSION.EMPRESA_VER,
  CRM_PERMISSION.PERFIL_VER,
];

const OFICINA_PERMISSIONS: readonly CrmPermission[] = [
  CRM_PERMISSION.DASHBOARD_VER,

  CRM_PERMISSION.CLIENTES_VER,
  CRM_PERMISSION.CLIENTES_CREAR,
  CRM_PERMISSION.CLIENTES_EDITAR,

  CRM_PERMISSION.INSTALACIONES_VER,
  CRM_PERMISSION.INSTALACIONES_CREAR,
  CRM_PERMISSION.INSTALACIONES_EDITAR,

  CRM_PERMISSION.TICKETS_VER,
  CRM_PERMISSION.SOPORTE_METAS_VER,
  CRM_PERMISSION.SOPORTE_CATEGORIAS_VER,

  CRM_PERMISSION.DESINSTALACIONES_VER,
  CRM_PERMISSION.DESINSTALACIONES_CREAR,
  CRM_PERMISSION.DESINSTALACIONES_AUTORIZAR,

  CRM_PERMISSION.SECTORES_VER,

  CRM_PERMISSION.BOT_VER,
  CRM_PERMISSION.WHATSAPP_VER,
  CRM_PERMISSION.WHATSAPP_GALERIA_VER,
  CRM_PERMISSION.WHATSAPP_PLANTILLAS_VER,
  CRM_PERMISSION.WHATSAPP_CAMPANAS_VER,

  CRM_PERMISSION.PLANTILLAS_CONTRATO_VER,

  CRM_PERMISSION.RUTAS_COBRO_VER,
  CRM_PERMISSION.RUTAS_ASIGNADAS_VER,

  CRM_PERMISSION.CREDITOS_VER,
  CRM_PERMISSION.CREDITOS_CREAR,

  CRM_PERMISSION.REGISTROS_ELIMINADOS_VER,

  CRM_PERMISSION.REPORTES_VER,

  CRM_PERMISSION.EMPRESA_VER,
  CRM_PERMISSION.PERFIL_VER,

  ...PPPOE_OFICINA_PERMISSIONS,
];

const COORDINADOR_PERMISSIONS: readonly CrmPermission[] = [
  ...ADMIN_PERMISSIONS,

  ...PPPOE_FULL_PERMISSIONS,
];

export const ROLE_PERMISSIONS: Record<RolUsuario, readonly CrmPermission[]> = {
  [RolUsuario.SUPER_ADMIN]: Object.values(CRM_PERMISSION),

  [RolUsuario.ADMIN]: ADMIN_PERMISSIONS,

  [RolUsuario.COORDINADOR_OPERACIONES]: COORDINADOR_PERMISSIONS,

  [RolUsuario.OFICINA]: OFICINA_PERMISSIONS,

  [RolUsuario.TIENDA]: [
    CRM_PERMISSION.DASHBOARD_VER,
    CRM_PERMISSION.CLIENTES_VER,
    CRM_PERMISSION.TICKETS_VER,
    CRM_PERMISSION.WHATSAPP_GALERIA_VER,
    CRM_PERMISSION.PERFIL_VER,
  ],

  [RolUsuario.TECNICO]: [
    CRM_PERMISSION.DASHBOARD_TECNICO_VER,
    CRM_PERMISSION.INSTALACIONES_TECNICO_VER,
    CRM_PERMISSION.TICKETS_VER,
    CRM_PERMISSION.PERFIL_VER,

    CRM_PERMISSION.TICKETS_TECNICO_GESTIONAR,
    CRM_PERMISSION.CLIENTES_VER,
  ],

  [RolUsuario.COBRADOR]: [
    CRM_PERMISSION.DASHBOARD_VER,

    CRM_PERMISSION.CLIENTES_VER,
    CRM_PERMISSION.CLIENTES_CREAR,

    CRM_PERMISSION.TICKETS_VER,

    CRM_PERMISSION.RUTAS_COBRO_VER,
    CRM_PERMISSION.RUTAS_ASIGNADAS_VER,

    CRM_PERMISSION.CREDITOS_VER,
    CRM_PERMISSION.CREDITOS_CREAR,

    CRM_PERMISSION.PERFIL_VER,
  ],
};
