export enum EstadoDesinstalacionCliente {
  PROGRAMADA = "PROGRAMADA",
  EN_PROCESO = "EN_PROCESO",
  COMPLETADA = "COMPLETADA",
  CANCELADA = "CANCELADA",
  FALLIDA = "FALLIDA",
}

export enum TipoDesinstalacionCliente {
  COMPLETA = "COMPLETA",
  PARCIAL = "PARCIAL",
  RETIRO_EQUIPO = "RETIRO_EQUIPO",
  CAMBIO_DOMICILIO = "CAMBIO_DOMICILIO",
  CANCELACION_SERVICIO = "CANCELACION_SERVICIO",
  OTRO = "OTRO",
}

export enum EstadoOperacionPppoe {
  PENDIENTE = "PENDIENTE",
  AUTORIZADA = "AUTORIZADA",
  EJECUTANDO = "EJECUTANDO",
  EXITOSA = "EXITOSA",
  PARCIAL = "PARCIAL",
  FALLIDA = "FALLIDA",
  CANCELADA = "CANCELADA",
}

export enum MotivoDesinstalacionCliente {
  VOLUNTARIA = "VOLUNTARIA",
  MORA = "MORA",
  CAMBIO_DOMICILIO = "CAMBIO_DOMICILIO",
  MAL_SERVICIO = "MAL_SERVICIO",
  FRAUDE = "FRAUDE",
  FALLA_TECNICA = "FALLA_TECNICA",
  CAMBIO_PROVEEDOR = "CAMBIO_PROVEEDOR",
  CLIENTE_NO_LOCALIZADO = "CLIENTE_NO_LOCALIZADO",
  OTRO = "OTRO",
}

export enum EstadoAutorizacionDesinstalacion {
  PENDIENTE = "PENDIENTE",
  APROBADA = "APROBADA",
  RECHAZADA = "RECHAZADA",
  ANULADA = "ANULADA",
}
